### ISSUE TITLE
App crash after add UI library to Podfile

### ISSUE THREAD

**Issue by hy9be** [dji-sdk/Mobile-UILibrary-iOS#7]
I add ``pod ‘DJI-UILibrary-iOS’, '~> 4.2’`` to my Podfile, run ``pod install`` and launch the app without any other code changes. The app crashed with information:
```
dyld: Library not loaded: @rpath/VideoPreviewer.framework/VideoPreviewer
  Referenced from: /private/var/containers/Bundle/Application/8DDEB1E6-4E6E-4FE0-B5A1-99765DFB9548/gridrone.app/Frameworks/DJIUILibrary.framework/DJIUILibrary
  Reason: image not found
```

**Comment by oliverou** [comment]
Hi @hy9be, it's not the UILibrary podfile issue. As you can see in the crash error, your Xcode project doesn't import the VideoPreviewer framework correctly. 

Please check this tutorial to learn how to import VideoPreviewer framework to your Xcode project: <http://developer.dji.com/mobile-sdk/documentation/ios-tutorials/index.html#importing-the-videopreviewer>

Also, we have a getting started tutorial for iOS UILibrary too, please check here: [Getting Started with DJI UI Library](http://developer.dji.com/mobile-sdk/documentation/ios-tutorials/UILibraryDemo.html).

**Comment by lbj96347** [comment]
@hy9be I faced the same issue with you. Finally I found the issue caused by the conflict between DJI SDK & DJI UILibrary. 

When I install DJI SDK 4.3.1 and DJI UI Library 4.2 at the same time, it would show the error like you post. After I upgrade my DJI SDK to 4.3.1 and UI Library to 4.3, everything is fine. 

Beside, I also test DJI UI Library 4.2 paired with DJI SDK 4.2.2, it worked well too. So, it may cause by the conflict. All in all, DJI UI Library should call the APIs from DJI SDK.
